#!/usr/bin/env python3
"""Validate actual shader-generator output for the two #193 pipeline recipes.

Usage: test-android-targeted-pnmtx.py DIR
DIR contains PIPELINE.dynamic.wgsl and PIPELINE.literal.wgsl generated by
build_shader using the same config, toggling only kartpadConstantPnMtx.
Private pipeline-cache payloads are deliberately not checked into the repo.
"""
import hashlib
from pathlib import Path
import re
import sys

BASELINES = {
    "58866e32bada1f83": "bad017e6a53cb06304af0aa9ee0285d8d2b9107c26e5c5fabc3155f1d2e554b2",
    "33c5ff18d5c180e0": "0c682289bfd23b08c9badea9109595f08e17728e9db3730cedf697dada560737",
}


def check(dynamic, literal):
    restored = literal
    for local, array, operand, count in (
        ("mv_pos", "postex_mtx", "vec4f(in_pos, 1.0)", 20),
        ("nrm_tmp", "nrm_mtx", "vec4f(in_nrm, 0.0)", 10),
    ):
        pattern = (rf"var {local} = vec3f\(0.0\);\n    switch \(in_pnmtxidx\) {{"
                   rf"(.*?)\n      default: {{ {local} = vec3f\(0.0\); }}\n    }}")
        matches = list(re.finditer(pattern, restored, re.S))
        assert len(matches) == 1, f"missing/duplicate switch for {local}"
        match = matches[0]
        cases = re.findall(r"case (\d+)u: \{ (.*?) \}", match.group(1))
        assert [int(slot) for slot, _ in cases] == list(range(count)), "palette coverage changed"
        for slot, expression in cases:
            assert expression == f"{local} = {operand} * ubuf.{array}[{slot}u];", "matrix selection or arithmetic changed"
        replacement = f"let {local} = {operand} * ubuf.{array}[in_pnmtxidx];"
        restored = restored[:match.start()] + replacement + restored[match.end():]
    assert restored == dynamic, "unrelated shader state changed"


def main():
    directory = Path(sys.argv[1])
    for pipeline, baseline in BASELINES.items():
        data = (directory / f"{pipeline}.dynamic.wgsl").read_bytes()
        assert hashlib.sha256(data).hexdigest() == baseline, "dynamic control differs from public85"
        dynamic = data.decode()
        literal = (directory / f"{pipeline}.literal.wgsl").read_text()
        check(dynamic, literal)
        for mutant in (literal.replace("postex_mtx[1u]", "postex_mtx[0u]", 1),
                       literal.replace("out.pos.z = -out.pos.z", "out.pos.z = out.pos.z", 1)):
            try:
                check(dynamic, mutant)
            except AssertionError:
                pass
            else:
                raise AssertionError("negative control was accepted")
        print(f"{pipeline}: public85 control identical; full palette and unrelated shader preserved; negative controls rejected")


if __name__ == "__main__":
    main()
